language: python
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py36
            python: 3.6
install: pip install tox
script: tox
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
